yolo_model:

  config_file:
    name: yolov3-isb-tidy.cfg
  weight_file:
    name: yolov3-isb-tidy.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      - doll_penguin
      - doll_pig
      - toy_car
      - doll_sheep
      - toy_airplane
      - sound_keyboard
      - block_cube_rits
      - doll_bear
      - doll_rabbit
      - block_cylind_wood
      - block_star
      - doll_monkey
      - sound_maracas
      - sound_whistle
      - toy_truck
